name: Deploy Stack
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy CloudFormation stack
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws cloudformation deploy \
          --template-file ./single-tier-app.yaml \
          --stack-name class-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            S3BucketName=lekunga-website-bucket \
          --region us-east-1
    - name: Sync with S3 Bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws s3 sync . s3://lekunga-website-bucket/ --exclude "*" --include "index.html" --region us-east-1

