name: Deploy Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy CloudFormation stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws cloudformation deploy \
            --template-file ./single-tier-app.yaml \
            --stack-name my-stack1 \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              S3BucketName=my-website1-bucket \
            --region us-east-1

    